package ca.nanometrics.gflot.client.options;

import com.google.gwt.core.client.JavaScriptObject;

import ca.nanometrics.gflot.client.Tick;
import ca.nanometrics.gflot.client.util.JSONHelper;
import ca.nanometrics.gflot.client.util.JSONObjectWrapper;

public abstract class AbstractAxisOptions
    extends JSONObjectWrapper
{
    public enum AxisPosition
    {
        TOP( "top" ), BOTTOM( "bottom" ), LEFT( "left" ), RIGHT( "right" );

        private String flotValue;

        AxisPosition( String flotValue )
        {
            this.flotValue = flotValue;
        }

        String getFlotValue()
        {
            return flotValue;
        }
    }

    /**
     * Set the visibility of the axis. By default, visibility is auto-detected, i.e. the axis will show up if there's
     * data associated with it.
     */
    public AbstractAxisOptions setShow( boolean show )
    {
        put( "show", show );
        return this;
    }

    /**
     * Set the overall placement of the legend within the plot ({@link #BOTTOM}, {@link #TOP}, {@link #LEFT},
     * {@link #RIGHT}). By default, the placement is {@link #BOTTOM} for x axis and {@link #LEFT} for y axis.
     */
    public AbstractAxisOptions setPosition( AxisPosition position )
    {
        assert null != position : "position can't be null";

        put( "position", position.getFlotValue() );
        return this;
    }

    /**
     * Set the color of the labels and ticks for the axis (default is the grid color). For more fine-grained control you
     * can also set the color of the ticks separately with {@link #setTickColor(String)} (otherwise it's autogenerated
     * as the base color with some transparency).
     */
    public AbstractAxisOptions setColor( String color )
    {
        put( "color", color );
        return this;
    }

    /**
     * Set the color of the ticks. By default, it's the color of the label with some transparency.
     */
    public AbstractAxisOptions setTickColor( String tickColor )
    {
        put( "tickColor", tickColor );
        return this;
    }

    /**
     * Set the precise minimum value on the scale. If you don't specify it, a value will automatically be chosen based
     * on the minimum data values. Note that Flot always examines all the data values you feed to it, even if a
     * restriction on another axis may make some of them invisible (this makes interactive use more stable).
     */
    public AbstractAxisOptions setMinimum( double min )
    {
        put( "min", new Double( min ) );
        return this;
    }

    /**
     * Set the precise maximum value on the scale. If you don't specify it, a value will automatically be chosen based
     * on the maximum data values. Note that Flot always examines all the data values you feed to it, even if a
     * restriction on another axis may make some of them invisible (this makes interactive use more stable).
     */
    public AbstractAxisOptions setMaximum( double max )
    {
        put( "max", new Double( max ) );
        return this;
    }

    /**
     * Set the autoscaleMargin. The "autoscaleMargin" is a bit esoteric: it's the fraction of margin that the scaling
     * algorithm will add to avoid that the outermost points ends up on the grid border. Note that this margin is only
     * applied when a min or max value is not explicitly set. If a margin is specified, the plot will furthermore extend
     * the axis end-point to the nearest whole tick. The default value is "null" for the x axes and 0.02 for y axes
     * which seems appropriate for most cases.
     */
    public AbstractAxisOptions setAutoscaleMargin( double margin )
    {
        put( "autoscaleMargin", new Double( margin ) );
        return this;
    }

    // TODO transform and inverseTransform

    /**
     * Set a fixed width on the tick label in pixels.
     */
    public AbstractAxisOptions setLabelWidth( double labelWidth )
    {
        put( "labelWidth", new Double( labelWidth ) );
        return this;
    }

    /**
     * Set a fixed height on the tick label in pixels.
     */
    public AbstractAxisOptions setLabelHeight( double labelHeight )
    {
        put( "labelHeight", new Double( labelHeight ) );
        return this;
    }

    /**
     * Set if Flot should reserve space for axis even if it's not shown. It is useful in combination with labelWidth and
     * labelHeight for aligning multi-axis charts.
     */
    public AbstractAxisOptions setReserveSpace( boolean reserveSpace )
    {
        put( "reserveSpace", reserveSpace );
        return this;
    }

    /**
     * Set how many ticks the tick generator algorithm aims for. The algorithm has two passes. It first estimates how
     * many ticks would be reasonable and uses this number to compute a nice round tick interval size. The algorithm
     * always tries to generate reasonably round tick values so even if you ask for three ticks, you might get five if
     * that fits better with the rounding. If you don't want any ticks at all, set to 0.
     */
    public AbstractAxisOptions setTicks( double ticks )
    {
        put( "ticks", new Double( ticks ) );
        return this;
    }

    /**
     * Set the ticks you want to show.
     */
    public AbstractAxisOptions setTicks( Tick[] ticks )
    {
        // TODO tick generator
        put( "ticks", JSONHelper.wrapArray( ticks ) );
        return this;
    }

    /**
     * Set the tick formatter.
     */
    public AbstractAxisOptions setTickFormatter( TickFormatter tickFormatter )
    {
        setTickFormatterNative( getWrappedObj().getJavaScriptObject(), tickFormatter );
        return this;
    }

    private static native void setTickFormatterNative( JavaScriptObject axisOptions, TickFormatter tickFormatter )
    /*-{
        axisOptions.tickFormatter = function(val, axis)
        {
            var jsonAxisObject = @com.google.gwt.json.client.JSONObject::new(Lcom/google/gwt/core/client/JavaScriptObject;)(axis);
            var javaAxisObject = @ca.nanometrics.gflot.client.Axis::new(Lcom/google/gwt/json/client/JSONObject;)(jsonAxisObject);
            return tickFormatter.@ca.nanometrics.gflot.client.options.TickFormatter::formatTickValue(DLca/nanometrics/gflot/client/Axis;)(val, javaAxisObject);
        };
    }-*/;

    /**
     * Set the length of the tick lines in pixels. By default, the innermost axes will have ticks that extend all across
     * the plot, while any extra axes use small ticks. A value of null means use the default, while a number means small
     * ticks of that length - set it to 0 to hide the lines completely.
     */
    public AbstractAxisOptions setTickLength( double tickLength )
    {
        put( "tickLength", new Double( tickLength ) );
        return this;
    }

    /**
     * If you set "alignTicksWithAxis" to the number of another axis, e.g. alignTicksWithAxis: 1, Flot will ensure that
     * the autogenerated ticks of this axis are aligned with the ticks of the other axis. This may improve the looks,
     * e.g. if you have one y axis to the left and one to the right, because the grid lines will then match the ticks in
     * both ends. The trade-off is that the forced ticks won't necessarily be at natural places.
     */
    public AbstractAxisOptions setAlignTicksWithAxis( double alignTicksWithAxis )
    {
        put( "alignTicksWithAxis", new Double( alignTicksWithAxis ) );
        return this;
    }

}
